/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllChatMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ChatMessage))],
      ['query'],
    ),
  'getInquiriesByEmail' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getRecentInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitChatMessage' : IDL.Func([IDL.Text], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllChatMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ChatMessage))],
        ['query'],
      ),
    'getInquiriesByEmail' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getRecentInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitChatMessage' : IDL.Func([IDL.Text], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };